services:
  hub:
    image: nginx:alpine
    container_name: hub
    restart: unless-stopped
    network_mode: host
    volumes:
      - /home/vineet/hub/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/vineet/hub/proxy_ws.conf:/etc/nginx/proxy_ws.conf:ro
      - /home/vineet/hub/html:/usr/share/nginx/html:ro
